apiVersion: v1
kind: Service
metadata:
  name: es-http-nodeport
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: es-transport-nodeport
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: elasticsearch
  ports:
  - name: transport
    port: 9300
    targetPort: 9300
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: kb-http-nodeport
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server-http-nodeport
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: apm-server
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-server-http-nodeport
spec:
  type: NodePort
  selector:
    agent.k8s.elastic.co/name: fleet-server
    common.k8s.elastic.co/type: agent
  ports:
  - name: http
    port: 8220
    targetPort: 8220
    nodePort: 30004