---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wolf-certs
  labels:
    app: elasticsearch
spec:
  secretName: wolf-certs
  dnsNames:
    - "blueteam.wolf"
    - "elasticsearch.wolf"
    - "kibana.wolf"
    - "fleet.wolf"
    - "apm.wolf"
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
  subject:
    organizations:
      - wolf
