# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ROLE_NAME}}"
subjects:
  - kind: ServiceAccount
    name: "{{SA_NAME}}"
roleRef:
  kind: Role
  name: "{{ROLE_NAME}}"
  apiGroup: rbac.authorization.k8s.io
